### ISSUE TITLE
Settle on a name

### ISSUE THREAD

**Issue by jdbann** [jdbann/shards.fyi#14]
Crystal Toolbox at the moment, but open to suggestions.

**Comment by edwardloveall** [comment]
Good idea. I wouldn't be disappointed with Toolbox but there is likely a better word representing categories of dependencies.

* ShardBase
* Crystal Catalog
* Shard Directory

**Comment by jdbann** [comment]
I prefer Crystal over Shard as the language name is probably more discoverable for beginners than the package name.

- **Base** seems too generic
- **Catalog** could work but my people would spell it catalogue 😛 
- **Directory** is nice
- **Toolbox** still holds weight for me as it hits on "the right tool for the job"
- **Armoury** could tap into that as well (but with Crystal is a bit fantasy)

**Comment by edwardloveall** [comment]
Hah, maybe we could push for en-us and en-gb translations 😛 

Yeah **Toolbox** is still pretty good. Something about just copying Ruby Toolbox rubs me the wrong way a little, but not so much that I would veto the name. I also have no problem with **Catalogue**. **Armoury** it a bit flowery for me, spelling not withstanding 😉.

**Directory** or **Toolbox** seem to be front runners. Directory is nice because it reminds me of Google or Yahoo's directories back in the early 2000s before search was the one way to find sites: https://en.wikipedia.org/wiki/Google_Directory

**Comment by edwardloveall** [comment]
Crystal Directory seems bad to me after giving it some distance.

**Comment by edwardloveall** [comment]
We could go with a single word, even made up like **Crystalarium**. Hard to spell maybe, but kind of memorable, I thnik.

Or perhaps a verb like **Crystalize**.

**Comment by jdbann** [comment]
I could be swayed on Shard. **ShardBase** as you suggested originally? **ShardBox**? **ShardShare**? **ShardKit**? **Shardvark**? **Shardenfreude**?

**Comment by paulcsmith** [comment]
FWIW I like shardbase and crystal toolbox :)

**Comment by jdbann** [comment]
Looking at domains, we'd have to hyphenate: shard-base.com or crystal-toolbox.com

Weird TLDs that might work:
http://shard.guide/
http://shard.tools/
http://shard.observer/
http://shards.fyi/

**Comment by edwardloveall** [comment]
First of all, Shardvark is brilliant. I'll also throw out **Shardcore** which has the same hyphenated domain name problem.

I like https://shard.fyi

It sorta keeps the theme from http://crystalshards.xyz and it has the feel of a reference site. That was always one of the goals in my head: to help people find the best shard for their project.

**Comment by jdbann** [comment]
Would you go singular or plural? shard.fyi or shards.fyi?

**Comment by edwardloveall** [comment]
Probably plural since there will be many shards on the site. Also when talking about the site, I imagine saying something like:

> If you want to find a bunch of information about _shards_, check out shards.fyi

**Comment by jdbann** [comment]
Completely agree - @paulcsmith?

**Comment by paulcsmith** [comment]
Super clever! Sounds good to me!

**Comment by jdbann** [comment]
Domain and twitter account registered. Will update the templates appropriately in the morning.
