### ISSUE TITLE
Get proper watchers count, remove subscriber count

### ISSUE THREAD

**Issue by edwardloveall** [jdbann/shards.fyi#20]
It looks like the counts that we see on the website are not what the are labeled in the API. From what I can tell, what we want is:

* Stars: `stargazers_count`
* Watchers: `subscribers_count`
* Forks: `forks_count`

I don't think there is a distinction between subscribers and watchers. They are one in the same.

Also, `watchers`, `watcher_count`, and `stargazers_count` all correspond to how many stars a repo has. If I star/unstar a repo, all three of those counts go up/down.

So, I think we should just stick to the three attributes listed above.

**Comment by jdbann** [comment]
Backed up by https://developer.github.com/v3/activity/watching/#watching-vs-starring
